services:
  demo-api:
    build:
      context: ./demo-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - docker-workshop
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 5
  ui:
    build:
      context: ./demo-react
      dockerfile: Dockerfile
    ports:
      - "8001:80"
  api_test:
    build: ./api-test
    tty: true
    volumes:
      - ./api-testing-report:/etc/newman/newman
    networks:
      - docker-workshop
    depends_on:
      demo-api:
        condition: service_healthy  # ✅ รอจนกว่า API พร้อม
networks:
  docker-workshop:
    driver: bridge
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: pass
#    depends_on:
#      - db
#  db:
#    image: mysql:9.2.0
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: mydb
#      MYSQL_USER: user
#      MYSQL_PASSWORD: pass
#    ports:
#      - "3306:3306"
#    restart: always
#    healthcheck:
#      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#      interval: 2s
#      timeout: 3s
#      retries: 5